web-app/firsthomework/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('rides/', include(('rides.urls', 'rides'), namespace='rides')),




    # path('rides/', include('rides.urls')),
]

web-app/rides/urls.py
from . import views
from django.urls import path
from .views import RideCreateView

app_name = 'rides'

urlpatterns = [
    # path('', views.home, name='rides-home'),
    path('ride-create/', RideCreateView.as_view(), name='ride-create'),
    path('ride-list/', views.OpenRideListView.as_view(), name='ride-list'),
    path('my-ride-list/', views.MyRidesView.as_view(), name='my-ride-list'),
    path('ride-detail/<int:pk>', views.RideDetailView.as_view(), name='ride-detail'),
    path('ride-edit/<int:pk>', views.RideEditView.as_view(), name='ride-edit'),
    path('ride/<int:pk>/cancel/', views.RideCancelView.as_view(), name='ride-cancel'),
    path('ride-join/<int:pk>', views.ride_join, name='ride-join'),
    path('driver-claim/<int:pk>/', views.driver_claim_ride, name='driver_claim_ride'),
    path('driver-complete/<int:pk>/', views.driver_complete_ride, name='driver_complete_ride'),
    path('ride/<int:pk>/quit/', views.RideQuitView.as_view(), name='ride-quit'),


]

web-app/rides/forms.py
from random import choices

from django import forms
from .models import Ride, RideShare





class RideRequestForm(forms.ModelForm):
    VEHICLE_TYPE_CHOICES = [
        ('', '--- Not Specified ---'),
        ('SUV', 'SUV'),
        ('SEDAN', 'SEDAN'),
        ('Hybrid', 'Hybrid'),
        ('VAN', 'VAN'),
        ('Truck', 'Truck'),
        ('Coupes', 'Coupes'),
        ('OTHER', 'Other'),
    ]

    vehicle_type_request = forms.ChoiceField(
        choices=VEHICLE_TYPE_CHOICES,
        required=False,
        widget=forms.Select(attrs={
            'class': 'form-control',
            'id': 'vehicleType',
            'onchange': "toggleOtherVehicle()"
        }),
        label='Vehicle Type',
    )

    other_vehicleType = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Specify Vehicle Type',
            'id': 'otherVehicleType',
            'style': 'display:none'
        }),
        label='Other Vehicle Type'
    )
    class Meta:
        model = Ride
        fields = ['destination', 'scheduled_datetime', 'owner_passengers',
                  'can_shared', 'special_request', 'vehicle_type_request']
        widgets = {
            'scheduled_datetime': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'class': 'form-control',
                'lang': 'en'
            }),
            'destination': forms.TextInput(attrs={'class': 'form-control'}),
            'owner_passengers': forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
            'can_shared': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'special_request': forms.TextInput(attrs={'class': 'form-control'}),
        }
    def clean(self):
        cleaned_data = super().clean()
        vehicle_type_request = cleaned_data.get('vehicle_type_request')
        other_vehicle_type = cleaned_data.get('other_vehicleType')
        if vehicle_type_request == 'OTHER':
            if not other_vehicle_type:
                self.add_error('other_vehicleType', 'Please enter a vehicle type.')
            else:
                cleaned_data['vehicle_type_request'] = other_vehicle_type

        return cleaned_data








class RideShareForm(forms.ModelForm):
    class Meta:
        model = RideShare
        fields = ['passenger']
        widgets = {
            'passenger': forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
        }



class BaseRideShareForm(forms.Form):
    earliest_datetime = forms.DateTimeField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
        label='Earliest Time'
    )
    latest_datetime = forms.DateTimeField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
        label='Latest Time'
    )


    def clean(self):
        cleaned_data = super().clean()
        earliest_datetime = cleaned_data.get('earliest_datetime')
        latest_datetime = cleaned_data.get('latest_datetime')


        if earliest_datetime and latest_datetime and earliest_datetime> latest_datetime:
            raise forms.ValidationError("The earliest time must be before the latest time.")
        return cleaned_data



class SearchRideShareForm(BaseRideShareForm):
    VEHICLE_TYPE_CHOICES = [
        ('SUV', 'SUV'),
        ('SEDAN', 'SEDAN'),
        ('Hybrid', 'Hybrid'),
        ('VAN', 'VAN'),
        ('Truck', 'Truck'),
        ('Coupes', 'Coupes'),
        ('OTHER', 'Other'),
    ]


    destination = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Destination'})
    )

    passengers_size = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
        label = 'Passengers Size'
    )


    vehicle_type = forms.ChoiceField(
        choices = VEHICLE_TYPE_CHOICES,
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Vehicle Type'
    )

    other_vehicleType = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Specify Vehicle Type'}),
        label='Other Vehicle Type'
    )



    def clean_passengers_size(self):
        passengers_size = self.cleaned_data.get('passengers_size')
        if passengers_size is not None and passengers_size < 1:
            raise forms.ValidationError("Passengers size must be at least 1.")
        return passengers_size
    def clean (self):
        cleaned_data = super().clean()
        vehicle_type = cleaned_data.get('vehicle_type')
        other_vehicle_type = cleaned_data.get('other_vehicleType')
        if vehicle_type == 'OTHER':
            if not other_vehicle_type:
                self.add_error('other_vehicleType', 'Please enter a vehicle type.')
            else:
                cleaned_data['vehicle_type'] = other_vehicle_type

        return cleaned_data

web-app/rides/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db import IntegrityError
from django.db.models import F, Q, Sum, Value
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from datetime import datetime


from .models import Ride, RideShare
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .forms import RideRequestForm,RideShareForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import DriverRequiredMixin, OwnerRequiredMixin

from django.db.models.functions import Coalesce
# Create your views here.
class OpenRideListView(ListView):
    model = Ride
    template_name = 'rides/ride_list.html'
    context_object_name = 'rides_list'
    paginate_by = 5
    ordering = ['-created_at']

    def get_queryset(self):
        qs = super().get_queryset().filter(
            Q(status=Ride.Status.OPEN)
        )
        # 使用 annotate 计算每个 Ride 的总乘客数：
        # 总乘客数 = owner_passengers + (所有 ride_share 中的 passenger 数量之和)
        # 使用 Coalesce 处理没有 ride_share 时 Sum 返回 None 的情况
        # ride_share__passenger表示访问 Ride 对象相关联的所有 RideShare 对象中的 passenger 字段
        # F函数：动态地获取值
        qs = qs.annotate(
            total_people=F('owner_passengers') + Coalesce(Sum('ride_share__passenger'), Value(0))
        )


        destination = self.request.GET.get('destination', '').strip()
        if destination:
            qs = qs.filter(destination__icontains=destination)

        # 到达时间区间搜索
        arrival_time_start = self.request.GET.get('arrival_time_start', '').strip()
        arrival_time_end = self.request.GET.get('arrival_time_end', '').strip()

        #  'YYYY-MM-DDTHH:MM'
        if arrival_time_start:
            try:
                start_datetime = datetime.strptime(arrival_time_start, '%Y-%m-%dT%H:%M')
                qs = qs.filter(scheduled_datetime__gte=start_datetime)
            except ValueError:
                pass

        if arrival_time_end:
            try:
                end_datetime = datetime.strptime(arrival_time_end, '%Y-%m-%dT%H:%M')
                qs = qs.filter(scheduled_datetime__lte=end_datetime)
            except ValueError:
                pass

        special_request = self.request.GET.get('special_request', '').strip()
        if special_request:
            qs = qs.filter(special_request__exact=special_request)

        cap_check = self.request.GET.get('cap_check', '').strip()
        if cap_check:

            qs = qs.filter(total_people__lte=cap_check)

        # 已经搭乘的乘客数量搜索
        passengers = self.request.GET.get('passengers', '').strip()
        if passengers:
            try:
                passengers = int(passengers)
                qs = qs.filter(total_people__exact=passengers)
            except ValueError:
                pass


        if self.request.user.is_authenticated:
            current_profile = self.request.user.userprofile
            # exclude the ride which user already join
            qs = qs.exclude(ride_share__sharer=current_profile)

            if not self.request.user.userprofile.is_driver:
                qs = qs.exclude(owner=current_profile).filter(can_shared=True)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['destination'] = self.request.GET.get('destination', '')
        context['arrival_time_start'] = self.request.GET.get('arrival_time_start', '')
        context['arrival_time_end'] = self.request.GET.get('arrival_time_end', '')
        context['passengers'] = self.request.GET.get('passengers', '')
        context['special_request'] = self.request.GET.get('special_request', '')
        context['cap_check'] = self.request.GET.get('cap_check', '')

        querydict = self.request.GET.copy()
        if 'page' in querydict:
            querydict.pop('page')
        context['query_string'] = querydict.urlencode()
        return context



class MyRidesView(ListView):
    model = Ride
    template_name = 'rides/my_ride_list.html'
    context_object_name = 'rides_list'
    paginate_by = 5
    ordering = ['-scheduled_datetime']

    def get_queryset(self):
        user = self.request.user
        user_profile = user.userprofile

        my_confirmed = self.request.GET.get("my_confirmed")
        if my_confirmed == 'on':
            if hasattr(user, 'driverprofile'):
                return Ride.objects.filter(driver=user.driverprofile, status="CONFIRMED")
            else:
                return Ride.objects.none()

        # 获取 GET 参数中的 status，如果有则使用该状态过滤
        status_query = self.request.GET.get('status')

        if status_query:
            owned = Ride.objects.filter(owner=user_profile, status=status_query)
            sharer_rides = RideShare.objects.filter(sharer=user_profile).select_related('ride')
            sharer = Ride.objects.filter(id__in=sharer_rides.values('ride_id'), status=status_query)
            driven = Ride.objects.none()
            if hasattr(user, 'driverprofile'):
                driven = Ride.objects.filter(driver=user.driverprofile, status=status_query)
        else:
        # 默认：排除 COMPLETED 状态
            owned = Ride.objects.filter(owner=user_profile).exclude(status=Ride.Status.COMPLETED)
            sharer_rides = RideShare.objects.filter(sharer=user_profile).select_related('ride')
            sharer = Ride.objects.filter(id__in=sharer_rides.values('ride_id')).exclude(status=Ride.Status.COMPLETED)
            driven = Ride.objects.none()
            if hasattr(user, 'driverprofile'):
                driven = Ride.objects.filter(driver=user.driverprofile).exclude(status=Ride.Status.COMPLETED)

        return owned.union(sharer, driven)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 将 Ride 模型的状态选项传递给模板
        context['ride_status_choices'] = Ride.Status.choices
        querydict = self.request.GET.copy()
        if 'page' in querydict:
            querydict.pop('page')
        context['query_string'] = querydict.urlencode()
        return context


class RideDetailView(DetailView):
    model = Ride
    template_name = 'rides/ride_detail.html'
    context_object_name = 'ride'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        ride = self.object

        if user.is_authenticated:
            if user.userprofile.is_driver:
                # see if the one who claim the ride is the exact driver of this ride
                context['driver_claimed'] = ride.driver == user.driverprofile
                # check if ride sharer list contains the driver(user)
                context['driver_join'] = ride.ride_share.filter(sharer = user.userprofile).exists()
            else:
                context['has_joined'] = ride.ride_share.filter(sharer=user.userprofile).exists()
        else:
            context['has_joined'] = False

        return context





# owner create ride
class RideCreateView(LoginRequiredMixin, CreateView):
    model = Ride
    form_class = RideRequestForm
    template_name = 'rides/ride_create.html'
    success_url = reverse_lazy('rides:my-ride-list')


    # logic for form created successfully
    def form_valid(self, form):
        form.instance.owner = self.request.user.userprofile

        form.instance.status = Ride.Status.OPEN
        return super().form_valid(form)


class RideCancelView(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = Ride
    template_name = 'rides/ride_cancel.html'
    success_url = reverse_lazy('rides:my-ride-list')
    fields = []
    def form_valid(self, form):
        if self.object.status == Ride.Status.OPEN:
            self.object = self.get_object()
            self.object.status = Ride.Status.CANCELLED
            self.object.save()
            messages.success(self.request, f"Ride #{self.object.id} has been cancelled")
        else:
            messages.error(self.request, f"Ride #{self.object.id} cannot be cancelled")
        return redirect('rides:my-ride-list')


class RideEditView(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = Ride
    form_class = RideRequestForm
    template_name = 'rides/ride_edit.html'
    success_url = reverse_lazy('rides:my-ride-list')
    def form_valid(self, form):
        if form.instance.status != Ride.Status.OPEN:
            messages.error(self.request, "Cannot edit this form")
            return redirect('rides:ride-list')
        return super().form_valid(form)


class RideQuitView(LoginRequiredMixin, DeleteView):
    model = RideShare
    template_name = 'rides/ride_quit.html'
    success_url = reverse_lazy('rides:my-ride-list')


    def get_object(self, queryset=None):
        ride_id = self.kwargs.get('pk')

        return get_object_or_404(RideShare, ride_id=ride_id, sharer=self.request.user.userprofile)


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        messages.success(request, f"Ride #{self.object.id} has been quit")
        return super().delete(request, *args, **kwargs)




@login_required()
def ride_join(request, pk):
    ride = get_object_or_404(Ride, pk=pk, status='OPEN', can_shared=True)
    user = request.user
    # reinforce logic
    if ride.owner == user.userprofile:
        messages.error(request, 'You cannot join your own ride')
        return redirect('rides:ride-list')
    if user.userprofile.is_driver and ride.driver == user.driverprofile:
        messages.error(request, 'You already claimed this ride')
        return redirect('rides:ride-list')
    if ride.ride_share.filter(sharer=user.userprofile).exists():
        messages.error(request, 'You have already joined this ride')
        return redirect('rides:ride-list')

web-app/rides/templates/rides/my_ride_list.html
<!-- rides/templates/rides/my_ride_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %}My Rides{% endblock %}

{% block content %}
<!-- Toggle  -->
<button class="btn btn-secondary mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#toggleSearch">
  Expand (collapse)
</button>

<div class="collapse show mb-3" id="toggleSearch">
  <div class="card card-body">
    <form method="get" class="row gx-3 gy-2 align-items-center">

      <div class="col-auto">
        <label for="status" class="visually-hidden">Status</label>
        <select class="form-select" name="status" id="status">
          <option value="">All</option>
          {% for key, value in ride_status_choices %}
            <option value="{{ key }}" {% if request.GET.status == key %}selected{% endif %}>{{ value }}</option>
          {% endfor %}
        </select>
      </div>


      <div class="col-auto form-check d-flex align-items-center">
        <input type="checkbox" class="form-check-input me-2" id="my_confirmed" name="my_confirmed"
               {% if request.GET.my_confirmed == "on" %} checked{% endif %}>
        <label for="my_confirmed" class="form-check-label">Show all my drive's ride</label>
      </div>


      <div class="col-auto">
        <button type="submit" class="btn btn-outline-primary">Search</button>
      </div>
    </form>
  </div>
</div>

<h2>My Rides</h2>


<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1{% if query_string %}&{{ query_string }}{% endif %}">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query_string %}&{{ query_string }}{% endif %}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">First</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Previous</a>
            </li>
        {% endif %}

        <li class="page-item active">
            <a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query_string %}&{{ query_string }}{% endif %}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if query_string %}&{{ query_string }}{% endif %}">Last</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Last</a>
            </li>
        {% endif %}
    </ul>
</nav>

{% if rides_list %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Destination</th>
        <th>Scheduled Time</th>
        <th>Owner</th>
        <th>Status</th>
        <th>Your role</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for ride in rides_list %}
      <tr>
        <td>{{ ride.id }}</td>
        <td>{{ ride.destination }}</td>
        <td>{{ ride.scheduled_datetime|date:"Y-m-d H:i" }}</td>
        <td>{{ ride.owner.name }}</td>
        <td>{{ ride.get_status_display }}</td>
        <td>
          {% if ride.owner == request.user.userprofile %}
            Owner
          {% elif ride.driver and ride.driver == request.user.driverprofile %}
            Driver
          {% else %}
            Sharer
          {% endif %}
        </td>
        <td>
          <a href="{% url 'rides:ride-detail' ride.id %}?from=my_ride_list{% if query_string %}&{{ query_string }}{% endif %}"
             class="btn btn-sm btn-info">
            Detail
          </a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No rides found.</p>
{% endif %}
{% endblock %}

web-app/rides/templates/rides/ride_cancel.html
<!-- rides/ride_cancel.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Confirm Delete Ride</h2>
  <p>Are you sure you want to delete the ride to "{{ object.destination }}" scheduled at "{{ object.scheduled_datetime }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Cancel</button>
    <a href="{% url 'rides:ride-detail' object.pk %}" class="btn btn-secondary">Back</a>
  </form>
{% endblock %}

web-app/rides/templates/rides/ride_create.html
<!-- rides/templates/rides/ride_create.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
  select option[value=""] {
    color: #999;
    font-style: italic;
  }
</style>
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2>Create New Ride</h2>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div>
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a href="{% url 'rides:ride-list' %}" class="btn btn-secondary">Cancel</a>
                </div>

            </form>
        </div>
    </div>
</div>


<script>
function toggleOtherVehicle() {
    const vehicleType = document.getElementById('vehicleType').value;
    const otherField = document.getElementById('otherVehicleType');

    if (vehicleType === 'OTHER') {
        otherField.parentElement.style.display = 'block';
        otherField.style.display = 'block';
        otherField.required = true;
    } else {
        otherField.parentElement.style.display = 'none';
        otherField.style.display = 'none';
<!--        otherField.required = false;-->
    }
}
document.addEventListener('DOMContentLoaded', toggleOtherVehicle);
</script>
{% endblock %}

web-app/rides/templates/rides/ride_detail.html
{% extends 'base.html' %}
{% block title %}Ride Detail{% endblock %}
{% block content %}

<h2>Ride #{{ ride.id }} - {{ ride.get_status_display }}</h2>
<div class="card">
  <div class="card-body">
    <p><strong>Destination:</strong> {{ ride.destination }}</p>
    <p><strong>Scheduled Time:</strong> {{ ride.scheduled_datetime|date:"Y-m-d H:i" }}</p>
    <p><strong>Owner:</strong> {{ ride.owner.name }}</p>
    <p><strong>Passengers (Owner):</strong> {{ ride.owner_passengers }}</p>
    <p><strong>Can Shared:</strong> {{ ride.can_shared }}</p>
    <p><strong>Special Request:</strong> {{ ride.special_request }}</p>
    {% if ride.vehicle_type_request %}
        <p><strong>Vehicle Type Request:</strong> {{ ride.vehicle_type_request }}</p>
    {% else %}
        <p><strong>Vehicle Type Request:</strong> None</p>
    {% endif %}



    {% if ride.driver %}
      <p><strong>Driver:</strong> {{ ride.driver.driver.username }} (capacity: {{ ride.driver.maxPassengers }}, License Plate: {{ ride.driver.licensePlate}})</p>
    {% else %}
      <p><strong>Driver:</strong> No driver claim this ride yet </p>
    {% endif %}


  {% if ride.status == 'CONFIRMED' and user.is_authenticated and user.userprofile.is_driver and driver_claimed %}
    <form action="{% url 'rides:driver_complete_ride' ride.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Complete Ride</button>
    </form>
  {% endif %}

<!--logic for Driver claim join Sharer join-->
   {% if ride.status == 'OPEN' and user.is_authenticated %}
<!--    owner-->
    {% if user.userprofile == ride.owner %}
      <div class="action-buttons">
        <p>This is your own ride, you can edit or cancel it</p>
        <a href="{% url 'rides:ride-edit' ride.pk %}?from={{ request.GET.from }}" class="btn btn-primary">Edit</a>
        <a href="{% url 'rides:ride-cancel' ride.pk %}" class="btn btn-danger">Cancel</a>
      </div>
    {% else %}
      <div class="action-buttons">
        {% if user.userprofile.is_driver %}
<!--          driver-->
          {% if driver_join %}
            <p>You have already joined this ride.</p>
          {% else %}
            <form method="post" action="{% url 'rides:driver_claim_ride' ride.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Claim</button>
            </form>
            <form method="post" action="{% url 'rides:ride-join' ride.pk %}" style="margin-top: 20px;">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Join</button>
            </form>
          {% endif %}
        {% else %}
<!--          sharer-->
          {% if not has_joined %}
            <form method="post" action="{% url 'rides:ride-join' ride.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Join</button>
            </form>
          {% else %}
            <div class="action-buttons">
              <a href="{% url 'rides:ride-quit' ride.pk %}" class="btn btn-danger">Quit</a>
            </div>
          {% endif %}
        {% endif %}
      </div>
    {% endif %}
  {% endif %}





    <div style="margin-top: 20px;">
      {% if request.GET.from == "my_ride_l" %}
        <a href="{% url 'rides:my-ride-list' %}" class="btn btn-primary">Back</a>
      {% elif request.GET.from == "ride_l" %}
        <a href="{% url 'rides:ride-list' %}" class="btn btn-primary">Back</a>
      {% endif %}
    </div>

  </div>
</div>

<h3 class="mt-4">Sharers</h3>
<ul class="list-group">
  {% for share in ride.ride_share.all %}
    <li class="list-group-item">
      {{ share.sharer.name }} (Party Size: {{ share.passenger }})
    </li>
  {% empty %}
    <li class="list-group-item">No Sharers yet.</li>
  {% endfor %}
</ul>


{% endblock %}

web-app/rides/templates/rides/ride_edit.html
<!-- templates/rides/ride_edit.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <h2>Edit Ride</h2>
  

  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save Changes</button>
    <a href="{% url 'rides:ride-detail' object.pk %}?from={{request.GET.from}}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock %}

web-app/rides/templates/rides/ride_join.html
{% extends 'base.html' %}

{% block content %}
<h1>Join Ride to {{ ride.destination }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm Join</button>
</form>
{% endblock %}

web-app/rides/templates/rides/ride_quit.html
<!-- rides/ride_quit.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Confirm Quit Ride</h2>
  <p>Are you sure you want to quit the ride to "{{ object.destination }}" scheduled at "{{ object.scheduled_datetime }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes</button>
    <a href="{% url 'rides:ride-detail' object.pk %}" class="btn btn-secondary">Back</a>
  </form>
{% endblock %}